{
 "title": "Catalyst POE Dashboard",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Interface",
    "query": "show tag values with key = \"intf_name\" WHERE (\"source\" =~ /^$switch$/)"
   },
   {
    "name": "switch",
    "query": "show tag values with key = \"source\""
   }
  ]
 },
 "panels": [
  {
   "title": "We are the",
   "type": "text",
   "gridPos": { "h": 8, "w": 21, "x": 0, "y": 0 },
   "options": {
    "content": "# PowerRangers \n\n![Image](https://variety.com/wp-content/uploads/2017/03/mighty-morphin-power-rangers.jpg)\t\n\n           "
   }
  },
  {
   "title": "Average power saved due to Power Save Mode",
   "type": "stat",
   "description": "Power saved due to Power save mode",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "Cisco-IOS-XE-poe-oper:poe-oper-data/poe-switch",
     "select": [
      [
       { "params": [ "consumed_poe_power" ], "type": "field" },
       {
        "params": [],
        "type": "spread"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$switch$/" }
     ]
    }
   ]
  },
  {
   "title": "Device Power SPREAD",
   "type": "stat",
   "description": "Power saved due to Power save mode",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "lala",
     "measurement": "Cisco-IOS-XE-poe-oper:poe-oper-data/poe-switch",
     "select": [
      [
       { "params": [ "consumed_poe_power" ], "type": "field" },
       {
        "params": [],
        "type": "spread"
       },
       { "params": [ "* $__interval_ms/1000/1000/2" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$switch$/" }
     ]
    }
   ]
  },
  {
   "title": "Dollars Saved for this Switch",
   "type": "stat",
   "description": "Power saved due to Power save mode",
   "gridPos": { "h": 9, "w": 5, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "Cisco-IOS-XE-poe-oper:poe-oper-data/poe-switch",
     "select": [
      [
       { "params": [ "consumed_poe_power" ], "type": "field" },
       {
        "params": [],
        "type": "spread"
       },
       {
        "params": [
         "* $__interval_ms/1000/1000/2*1.05"
        ],
        "type": "math"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$switch$/" }
     ]
    }
   ]
  },
  {
   "title": "CO2 Saved",
   "type": "stat",
   "description": "Power saved due to Power save mode",
   "gridPos": { "h": 9, "w": 5, "x": 17, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "masskg" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } }
  },
  { "title": "Switch Total", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Total Power Consumed - grouped in 10 min intervals",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 22, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "alias": "Consumed Power",
     "groupBy": [
      { "params": [ "10m" ], "type": "time" }
     ],
     "measurement": "Cisco-IOS-XE-poe-oper:poe-oper-data/poe-switch",
     "select": [
      [
       { "params": [ "consumed_poe_power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$switch$/" }
     ]
    }
   ]
  },
  {
   "title": "Per port consumption",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 22, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "alias": "$tag_intf_name",
     "groupBy": [
      { "params": [ "30m" ], "type": "time" },
      { "params": [ "intf_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Cisco-IOS-XE-poe-oper:poe-oper-data/poe-port-detail",
     "select": [
      [
       { "params": [ "power_consumption" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "intf_name", "operator": "=~", "value": "/^$Interface$/" },
      { "condition": "AND", "key": "source", "operator": "=~", "value": "/^$switch$/" }
     ]
    }
   ]
  },
  {
   "title": "Port Power Consumption - NS edit",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "15m" ], "type": "time" }
     ],
     "measurement": "Cisco-IOS-XE-poe-oper:poe-oper-data/poe-port-detail",
     "select": [
      [
       { "params": [ "power_consumption" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "source", "operator": "=~", "value": "/^$switch$/" },
      { "condition": "AND", "key": "intf_name", "operator": "=~", "value": "/^$Interface$/" }
     ]
    }
   ]
  },
  {
   "title": "Device Power",
   "type": "graph",
   "gridPos": { "h": 15, "w": 11, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "alias": "[[tag_name]] $col",
     "groupBy": [
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "Cisco-IOS-XE-poe-oper:poe-oper-data/poe-switch",
     "select": [
      [
       { "params": [ "available_power" ], "type": "field" }
      ],
      [
       { "params": [ "consumed_system_power" ], "type": "field" }
      ],
      [
       { "params": [ "power_budget" ], "type": "field" }
      ],
      [
       { "params": [ "power_allocated" ], "type": "field" }
      ],
      [
       { "params": [ "consumed_poe_power" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$switch$/" }
     ]
    }
   ]
  },
  { "title": "Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "Map CDP and PoE",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 56 },
   "targets": [
    {
     "query": "SELECT local_intf_name as intf_name, device_name, source FROM \"Cisco-IOS-XE-cdp-oper:cdp-neighbor-details/cdp-neighbor-detail\" WHERE (\"source\" =~ /^$switch$/) group by *"
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Cisco-IOS-XE-poe-oper:poe-oper-data/poe-port-detail",
     "query": "select power_consumption,max_power_drawn, last(\"device_name\") AS \"intf_name\" from \"Cisco-IOS-XE-poe-oper:poe-oper-data/poe-port-detail\"  WHERE (\"source\" =~ /^$switch$/) group by *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Ignore beow", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 } },
  {
   "title": "Ignore",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 },
   "collapsed": true,
   "panels": [
    {
     "title": "CDP",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 88 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "Cisco-IOS-XE-poe-oper:poe-oper-data/poe-port-detail",
       "query": "select *, last(\"device_name\") AS \"intf_name\" from \"Cisco-IOS-XE-cdp-oper:cdp-neighbor-details/cdp-neighbor-detail\"  WHERE (\"source\" =~ /^$switch$/)  group by *",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "POE Interface",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 96 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "Cisco-IOS-XE-poe-oper:poe-oper-data/poe-port-detail",
       "query": "select *, last(\"device_name\") AS \"intf_name\" from \"Cisco-IOS-XE-poe-oper:poe-oper-data/poe-port-detail\"  WHERE (\"source\" =~ /^$switch$/) group by *",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Inlet Temp",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 104 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "alias": "Inlet Temp",
       "measurement": "Cisco-IOS-XE-environment-oper:environment-sensors/environment-sensor",
       "select": [
        [
         { "params": [ "current_reading" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "name", "operator": "=", "value": "Inlet Temp Sensor" },
        { "condition": "AND", "key": "source", "operator": "=~", "value": "/^$switch$/" }
       ]
      }
     ]
    },
    {
     "title": "Outlet Temp",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 3, "y": 104 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "alias": "HotSpot Temp",
       "measurement": "Cisco-IOS-XE-environment-oper:environment-sensors/environment-sensor",
       "select": [
        [
         { "params": [ "current_reading" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "name", "operator": "=", "value": "Outlet Temp Sensor" },
        { "condition": "AND", "key": "source", "operator": "=~", "value": "/^$switch$/" }
       ]
      }
     ]
    },
    {
     "title": "HotSpot Temp",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 6, "y": 104 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "alias": "HotSpot Temp",
       "measurement": "Cisco-IOS-XE-environment-oper:environment-sensors/environment-sensor",
       "select": [
        [
         { "params": [ "current_reading" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "name", "operator": "=", "value": "HotSpot Temp Sensor" },
        { "condition": "AND", "key": "source", "operator": "=~", "value": "/^$switch$/" }
       ]
      }
     ]
    },
    {
     "title": "Port Power Consumption",
     "type": "timeseries",
     "gridPos": { "h": 15, "w": 11, "x": 0, "y": 107 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "targets": [
      {
       "alias": "$col",
       "measurement": "Cisco-IOS-XE-poe-oper:poe-oper-data/poe-port-detail",
       "select": [
        [
         { "params": [ "power_consumption" ], "type": "field" }
        ],
        [
         { "params": [ "max_power_drawn" ], "type": "field" }
        ],
        [
         { "params": [ "power_used" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "intf_name", "operator": "=~", "value": "/^$Interface$/" },
        { "condition": "AND", "key": "source", "operator": "=~", "value": "/^$switch$/" }
       ]
      }
     ]
    },
    {
     "title": "Device Power",
     "type": "timeseries",
     "gridPos": { "h": 15, "w": 11, "x": 1, "y": 122 },
     "targets": [
      {
       "alias": "[[tag_name]] $col",
       "groupBy": [
        { "params": [ "name" ], "type": "tag" }
       ],
       "measurement": "Cisco-IOS-XE-poe-oper:poe-oper-data/poe-switch",
       "select": [
        [
         { "params": [ "consumed_poe_power" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "source", "operator": "=~", "value": "/^$switch$/" }
       ]
      }
     ]
    }
   ]
  }
 ]
}